INSERT INTO CONTENT (ContentID, AdminID, Title, Description, ReleaseDate, ContentType, GenreID) VALUES
(1, 2, 'Kalki 2898 AD', 'Mythological sci-fi epic.', '2024-06-27', 'Platinum', 5),
(2, 2, 'Animal', 'Intense emotional action drama.', '2023-12-01', 'Platinum', 1),
(3, 2, 'Jawan', 'A vigilante takes on corrupt systems.', '2023-09-07', 'Gold', 1),
(4, 2, 'Pushpa 2', 'A smuggler’s rise continues.', '2025-08-15', 'Platinum', 6),
(5, 2, 'Bhool Bhulaiyaa 2', 'A haunted palace brings chaos.', '2022-05-20', 'Gold', 2),
(6, 2, 'Drishyam 2', 'Secrets unfold in this crime thriller.', '2022-11-18', 'Gold', 3),
(7, 2, 'Brahmastra', 'Young man with supernatural power.', '2022-09-09', 'Platinum', 5),
(8, 2, 'Rocky Aur Rani Ki Prem Kahani', 'Love story of different cultures.', '2023-07-28', 'Silver', 4),
(9, 2, 'Sita Ramam', 'Romantic story via letters.', '2022-08-05', 'Gold', 4),
(10, 2, 'Salaar', 'Dystopian action-packed revenge.', '2023-12-22', 'Platinum', 1),
(11, 2, 'KGF Chapter 2', 'Gold mafia rises again.', '2022-04-14', 'Platinum', 1),
(12, 2, 'Gadar 2', 'A man returns for his son.', '2023-08-11', 'Gold', 1),
(13, 2, 'Mission Raniganj', 'Mining disaster rescue mission.', '2023-10-06', 'Gold', 6),
(14, 2, 'Pathaan', 'Spy action across continents.', '2023-01-25', 'Platinum', 1),
(15, 2, 'Vikram Vedha', 'Cop vs gangster mind game.', '2022-09-30', 'Gold', 3),
(16, 2, 'Shamshera', 'Freedom fighter against tyranny.', '2022-07-22', 'Silver', 1),
(17, 2, 'Dasara', 'Alcohol politics and revenge.', '2023-03-30', 'Gold', 6),
(18, 2, 'Kantara', 'Myth and folklore meet reality.', '2022-09-30', 'Gold', 4),
(19, 2, 'Hi Nanna', 'Emotional father-daughter bond.', '2023-12-07', 'Silver', 4),
(20, 2, 'Dunki', 'Illegal immigration journey.', '2023-12-21', 'Platinum', 4),

(21, 2, 'Jigarthanda DoubleX', 'Gangster filmmaker clash.', '2023-11-10', 'Gold', 1),
(22, 2, 'Bheeshma', 'Comedy about organic farming.', '2020-02-21', 'Silver', 2),
(23, 2, 'Sarkaru Vaari Paata', 'Bank fraud and action.', '2022-05-12', 'Silver', 3),
(24, 2, 'Love Story', 'Dance and caste battle.', '2021-09-24', 'Gold', 4),
(25, 2, 'Uppena', 'Fisherman in love across caste.', '2021-02-12', 'Silver', 4),
(26, 2, 'Major', 'Based on Major Sandeep Unnikrishnan.', '2022-06-03', 'Platinum', 6),
(27, 2, 'Freddy', 'Dentist turns dark.', '2022-12-02', 'Gold', 3),
(28, 2, 'Goodbye', 'Loss and life journey.', '2022-10-07', 'Silver', 4),
(29, 2, 'RRR', 'Two heroes fight colonial rule.', '2022-03-25', 'Platinum', 1),
(30, 2, 'CID 999', 'Detective hunts a criminal.', '2025-06-30', 'Platinum', 6);

INSERT INTO MOVIE (MovieID, DurationInMinutes, TrailerURL, PosterURL, OverallRating, VideoURL) VALUES
(1, 180, '~/Content/Images/VideoImg/Kalki2898ADVideo.png', '~/Content/Images/PosterImg/Kalki2898AD.png', 4.5, '~/Content/Images/VideoImg/Kalki2898ADVideo.png'),
(2, 201, '~/Content/Images/VideoImg/AnimalVideo.png', '~/Content/Images/PosterImg/Animal.png', 4.8, '~/Content/Images/VideoImg/AnimalVideo.png'),
(3, 169, '~/Content/Images/VideoImg/JawanVideo.png', '~/Content/Images/PosterImg/Jawan.png', 4.2, '~/Content/Images/VideoImg/JawanVideo.png'),
(4, 150, '~/Content/Images/VideoImg/Pushpa2Video.png', '~/Content/Images/PosterImg/Pushpa2.png', 4.9, '~/Content/Images/VideoImg/Pushpa2Video.png'),
(5, 145, '~/Content/Images/VideoImg/BhoolBhulaiyaa2Video.png', '~/Content/Images/PosterImg/BhoolBhulaiyaa2.png', 3.8, '~/Content/Images/VideoImg/BhoolBhulaiyaa2Video.png'),
(6, 140, '~/Content/Images/VideoImg/Drishyam2Video.png', '~/Content/Images/PosterImg/Drishyam2.png', 4.7, '~/Content/Images/VideoImg/Drishyam2Video.png'),
(7, 167, '~/Content/Images/VideoImg/BrahmastraVideo.png', '~/Content/Images/PosterImg/Brahmastra.png', 3.6, '~/Content/Images/VideoImg/BrahmastraVideo.png'),
(8, 168, '~/Content/Images/VideoImg/RockyAurRaniKiPremKahaniVideo.png', '~/Content/Images/PosterImg/RockyAurRaniKiPremKahani.png', 4.0, '~/Content/Images/VideoImg/RockyAurRaniKiPremKahaniVideo.png'),
(9, 163, '~/Content/Images/VideoImg/SitaRamamVideo.png', '~/Content/Images/PosterImg/SitaRamam.png', 4.9, '~/Content/Images/VideoImg/SitaRamamVideo.png'),
(10, 172, '~/Content/Images/VideoImg/SalaarVideo.png', '~/Content/Images/PosterImg/Salaar.png', 4.4, '~/Content/Images/VideoImg/SalaarVideo.png'),

(11, 168, '~/Content/Images/VideoImg/KGFChapter2Video.png', '~/Content/Images/PosterImg/KGFChapter2.png', 4.7, '~/Content/Images/VideoImg/KGFChapter2Video.png'),
(12, 155, '~/Content/Images/VideoImg/Gadar2Video.png', '~/Content/Images/PosterImg/Gadar2.png', 4.1, '~/Content/Images/VideoImg/Gadar2Video.png'),
(13, 130, '~/Content/Images/VideoImg/MissionRaniganjVideo.png', '~/Content/Images/PosterImg/MissionRaniganj.png', 4.3, '~/Content/Images/VideoImg/MissionRaniganjVideo.png'),
(14, 146, '~/Content/Images/VideoImg/PathaanVideo.png', '~/Content/Images/PosterImg/Pathaan.png', 4.0, '~/Content/Images/VideoImg/PathaanVideo.png'),
(15, 160, '~/Content/Images/VideoImg/VikramVedhaVideo.png', '~/Content/Images/PosterImg/VikramVedha.png', 4.5, '~/Content/Images/VideoImg/VikramVedhaVideo.png'),
(16, 159, '~/Content/Images/VideoImg/ShamsheraVideo.png', '~/Content/Images/PosterImg/Shamshera.png', 3.4, '~/Content/Images/VideoImg/ShamsheraVideo.png'),
(17, 156, '~/Content/Images/VideoImg/DasaraVideo.png', '~/Content/Images/PosterImg/Dasara.png', 4.6, '~/Content/Images/VideoImg/DasaraVideo.png'),
(18, 147, '~/Content/Images/VideoImg/KantaraVideo.png', '~/Content/Images/PosterImg/Kantara.png', 5.0, '~/Content/Images/VideoImg/KantaraVideo.png'),
(19, 143, '~/Content/Images/VideoImg/HiNannaVideo.png', '~/Content/Images/PosterImg/HiNanna.png', 4.3, '~/Content/Images/VideoImg/HiNannaVideo.png'),
(20, 161, '~/Content/Images/VideoImg/DunkiVideo.png', '~/Content/Images/PosterImg/Dunki.png', 4.2, '~/Content/Images/VideoImg/DunkiVideo.png'),

(21, 150, '~/Content/Images/VideoImg/JigarthandaDoubleXVideo.png', '~/Content/Images/PosterImg/JigarthandaDoubleX.png', 4.1, '~/Content/Images/VideoImg/JigarthandaDoubleXVideo.png'),
(22, 148, '~/Content/Images/VideoImg/BheeshmaVideo.png', '~/Content/Images/PosterImg/Bheeshma.png', 3.9, '~/Content/Images/VideoImg/BheeshmaVideo.png'),
(23, 145, '~/Content/Images/VideoImg/SarkaruVaariPaataVideo.png', '~/Content/Images/PosterImg/SarkaruVaariPaata.png', 3.6, '~/Content/Images/VideoImg/SarkaruVaariPaataVideo.png'),
(24, 154, '~/Content/Images/VideoImg/LoveStoryVideo.png', '~/Content/Images/PosterImg/LoveStory.png', 4.0, '~/Content/Images/VideoImg/LoveStoryVideo.png'),
(25, 142, '~/Content/Images/VideoImg/UppenaVideo.png', '~/Content/Images/PosterImg/Uppena.png', 3.7, '~/Content/Images/VideoImg/UppenaVideo.png'),
(26, 150, '~/Content/Images/VideoImg/MajorVideo.png', '~/Content/Images/PosterImg/Major.png', 4.8, '~/Content/Images/VideoImg/MajorVideo.png'),
(27, 128, '~/Content/Images/VideoImg/FreddyVideo.png', '~/Content/Images/PosterImg/Freddy.png', 3.5, '~/Content/Images/VideoImg/FreddyVideo.png'),
(28, 132, '~/Content/Images/VideoImg/GoodbyeVideo.png', '~/Content/Images/PosterImg/Goodbye.png', 3.9, '~/Content/Images/VideoImg/GoodbyeVideo.png'),
(29, 182, '~/Content/Images/VideoImg/RRRVideo.png', '~/Content/Images/PosterImg/RRR.png', 4.9, '~/Content/Images/VideoImg/RRRVideo.png'),
(30, 140, '~/Content/Images/VideoImg/CID999Video.png', '~/Content/Images/PosterImg/CID999.png', 4.4, '~/Content/Images/VideoImg/CID999Video.png');
